export * from '../../protocols/index'
export * from '../../protocols/email-validator'
export * from '../../protocols/id-validator'
export * from '../../protocols/register-code-validator'
export * from '../../../domain/usecases/link-student-person'
